### ISSUE TITLE
[iOS] 검색결과 TableView CustomCell

### ISSUE THREAD

**Issue by piggyse** [leejohy-0223/airbnb#12]
## 💡 issue
Custom Cell 제작

## 📝 todo
- [x] Custom Header 제작
- [x] Custom Cell 제작
- [x] Layout 및 폰트 적용
