### ISSUE TITLE
[iOS] MapView Card Custom Cell 구현

### ISSUE THREAD

**Issue by piggyse** [leejohy-0223/airbnb#8]
## 💡 issue
MapView 위에 올라갈 CollectionView의 Custom Cell구현

## 📝 todo
- [x] 이미지, lable들 생성 및 레이아웃 잡기
- [x] 별표 이미지, 후기 Label Text 속성 각각 다르게 만들기
- [x] 하트(찜) 버튼 생성, 액션추가
